version: '3'

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - metadata
      - storage
    networks:
      - ctfnet

  metadata:
    build: ./metadata
    container_name: metadata
    networks:
      - ctfnet
    volumes:
      - type: tmpfs
        target: /data

  storage:
    build: ./storage
    container_name: storage
    networks:
      - ctfnet
    volumes:
      - type: tmpfs
        target: /data

networks:
  ctfnet:
