version: '3.8'

services:
  app:
    build: ./app
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      - metadata
      - storage
    networks:
      - ctfnet
    restart: always

  metadata:
    build: ./metadata
    container_name: metadata
    networks:
      - ctfnet
    volumes:
      - shared-data:/data
    restart: always

  storage:
    build: ./storage
    container_name: storage
    networks:
      - ctfnet
    volumes:
      - shared-data:/data
    restart: always

networks:
  ctfnet:
    driver: bridge

volumes:
  shared-data:
