version: '3'

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - metadata
      - storage

  metadata:
    build: ./metadata
    container_name: metadata
    environment:
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}

  storage:
    build: ./storage
    container_name: storage
    environment:
      - ACCESS_KEY=MBROWGXXIPAJCJAX
      - SECRET_KEY=mO0pmOoXValvt8PhT9OJwaVSXzrkoBs9
